# Generated by Django 5.0 on 2024-04-03 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_genere_image'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritemovie',
            name='genere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finalapp.genere'),
            preserve_default=False,
        ),
    ]
