# Generated by Django 5.0 on 2024-04-03 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_genere_image'),
        ('userapp', '0003_alter_favouritemovie_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritemovie',
            unique_together={('user', 'movie')},
        ),
        migrations.RemoveField(
            model_name='favouritemovie',
            name='genere',
        ),
    ]
