# Generated by Django 5.0 on 2024-04-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
