# Generated by Django 5.0 on 2024-04-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='genere',
            name='image',
            field=models.ImageField(default=2, upload_to='genere'),
            preserve_default=False,
        ),
    ]
